//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IstaNoteClient.IstaNoteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteStatusOptions", Namespace="https://services.ista-billing.com/api")]
    public enum NoteStatusOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotePriorityOptions", Namespace="https://services.ista-billing.com/api")]
    public enum NotePriorityOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Term = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Final = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteCallTypeOptions", Namespace="https://services.ista-billing.com/api")]
    public enum NoteCallTypeOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inbound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCall = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteDTO", Namespace="https://services.ista-billing.com/api")]
    [System.SerializableAttribute()]
    public partial class NoteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NoteIdField;
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteTypeDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private System.DateTime CallBeginField;
        
        private System.DateTime CallEndField;
        
        private System.DateTime CallClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IstaNoteClient.IstaNoteService.NoteDetailDTO[] DetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NoteId {
            get {
                return this.NoteIdField;
            }
            set {
                if ((this.NoteIdField.Equals(value) != true)) {
                    this.NoteIdField = value;
                    this.RaisePropertyChanged("NoteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NoteType {
            get {
                return this.NoteTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteTypeField, value) != true)) {
                    this.NoteTypeField = value;
                    this.RaisePropertyChanged("NoteType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string NoteTypeDetail {
            get {
                return this.NoteTypeDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteTypeDetailField, value) != true)) {
                    this.NoteTypeDetailField = value;
                    this.RaisePropertyChanged("NoteTypeDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CallType {
            get {
                return this.CallTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CallTypeField, value) != true)) {
                    this.CallTypeField = value;
                    this.RaisePropertyChanged("CallType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime CallBegin {
            get {
                return this.CallBeginField;
            }
            set {
                if ((this.CallBeginField.Equals(value) != true)) {
                    this.CallBeginField = value;
                    this.RaisePropertyChanged("CallBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime CallEnd {
            get {
                return this.CallEndField;
            }
            set {
                if ((this.CallEndField.Equals(value) != true)) {
                    this.CallEndField = value;
                    this.RaisePropertyChanged("CallEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime CallClosed {
            get {
                return this.CallClosedField;
            }
            set {
                if ((this.CallClosedField.Equals(value) != true)) {
                    this.CallClosedField = value;
                    this.RaisePropertyChanged("CallClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public IstaNoteClient.IstaNoteService.NoteDetailDTO[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteDetailDTO", Namespace="https://services.ista-billing.com/api")]
    [System.SerializableAttribute()]
    public partial class NoteDetailDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NoteDetailIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteDetailTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NoteDetailId {
            get {
                return this.NoteDetailIdField;
            }
            set {
                if ((this.NoteDetailIdField.Equals(value) != true)) {
                    this.NoteDetailIdField = value;
                    this.RaisePropertyChanged("NoteDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NoteDetailText {
            get {
                return this.NoteDetailTextField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteDetailTextField, value) != true)) {
                    this.NoteDetailTextField = value;
                    this.RaisePropertyChanged("NoteDetailText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://services.ista-billing.com/api", ConfigurationName="IstaNoteService.NoteSoap")]
    public interface NoteSoap {
        
        // CODEGEN: Generating message contract since element name accountNo from namespace https://services.ista-billing.com/api is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://services.ista-billing.com/api/Create", ReplyAction="*")]
        IstaNoteClient.IstaNoteService.CreateResponse Create(IstaNoteClient.IstaNoteService.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.ista-billing.com/api/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.CreateResponse> CreateAsync(IstaNoteClient.IstaNoteService.CreateRequest request);
        
        // CODEGEN: Generating message contract since element name accountNo from namespace https://services.ista-billing.com/api is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://services.ista-billing.com/api/List", ReplyAction="*")]
        IstaNoteClient.IstaNoteService.ListResponse List(IstaNoteClient.IstaNoteService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.ista-billing.com/api/List", ReplyAction="*")]
        System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.ListResponse> ListAsync(IstaNoteClient.IstaNoteService.ListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="https://services.ista-billing.com/api", Order=0)]
        public IstaNoteClient.IstaNoteService.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(IstaNoteClient.IstaNoteService.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://services.ista-billing.com/api")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public IstaNoteClient.IstaNoteService.NoteStatusOptions noteStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public IstaNoteClient.IstaNoteService.NotePriorityOptions notePriority;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int noteTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int noteTypeDetailId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int noteDepartmentId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int openByUserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime callBegin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime callEnd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime closeDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public IstaNoteClient.IstaNoteService.NoteCallTypeOptions callType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string noteText;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(string accountNo, IstaNoteClient.IstaNoteService.NoteStatusOptions noteStatus, IstaNoteClient.IstaNoteService.NotePriorityOptions notePriority, int noteTypeID, int noteTypeDetailId, int noteDepartmentId, int openByUserId, System.DateTime callBegin, System.DateTime callEnd, System.DateTime closeDate, IstaNoteClient.IstaNoteService.NoteCallTypeOptions callType, string noteText) {
            this.accountNo = accountNo;
            this.noteStatus = noteStatus;
            this.notePriority = notePriority;
            this.noteTypeID = noteTypeID;
            this.noteTypeDetailId = noteTypeDetailId;
            this.noteDepartmentId = noteDepartmentId;
            this.openByUserId = openByUserId;
            this.callBegin = callBegin;
            this.callEnd = callEnd;
            this.closeDate = closeDate;
            this.callType = callType;
            this.noteText = noteText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="https://services.ista-billing.com/api", Order=0)]
        public IstaNoteClient.IstaNoteService.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(IstaNoteClient.IstaNoteService.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateResponseBody {
        
        public CreateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="https://services.ista-billing.com/api", Order=0)]
        public IstaNoteClient.IstaNoteService.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(IstaNoteClient.IstaNoteService.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://services.ista-billing.com/api")]
    public partial class ListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int customerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountNo;
        
        public ListRequestBody() {
        }
        
        public ListRequestBody(int customerId, string accountNo) {
            this.customerId = customerId;
            this.accountNo = accountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="https://services.ista-billing.com/api", Order=0)]
        public IstaNoteClient.IstaNoteService.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(IstaNoteClient.IstaNoteService.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://services.ista-billing.com/api")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IstaNoteClient.IstaNoteService.NoteDTO[] ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(IstaNoteClient.IstaNoteService.NoteDTO[] ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoteSoapChannel : IstaNoteClient.IstaNoteService.NoteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoteSoapClient : System.ServiceModel.ClientBase<IstaNoteClient.IstaNoteService.NoteSoap>, IstaNoteClient.IstaNoteService.NoteSoap {
        
        public NoteSoapClient() {
        }
        
        public NoteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IstaNoteClient.IstaNoteService.CreateResponse IstaNoteClient.IstaNoteService.NoteSoap.Create(IstaNoteClient.IstaNoteService.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public void Create(string accountNo, IstaNoteClient.IstaNoteService.NoteStatusOptions noteStatus, IstaNoteClient.IstaNoteService.NotePriorityOptions notePriority, int noteTypeID, int noteTypeDetailId, int noteDepartmentId, int openByUserId, System.DateTime callBegin, System.DateTime callEnd, System.DateTime closeDate, IstaNoteClient.IstaNoteService.NoteCallTypeOptions callType, string noteText) {
            IstaNoteClient.IstaNoteService.CreateRequest inValue = new IstaNoteClient.IstaNoteService.CreateRequest();
            inValue.Body = new IstaNoteClient.IstaNoteService.CreateRequestBody();
            inValue.Body.accountNo = accountNo;
            inValue.Body.noteStatus = noteStatus;
            inValue.Body.notePriority = notePriority;
            inValue.Body.noteTypeID = noteTypeID;
            inValue.Body.noteTypeDetailId = noteTypeDetailId;
            inValue.Body.noteDepartmentId = noteDepartmentId;
            inValue.Body.openByUserId = openByUserId;
            inValue.Body.callBegin = callBegin;
            inValue.Body.callEnd = callEnd;
            inValue.Body.closeDate = closeDate;
            inValue.Body.callType = callType;
            inValue.Body.noteText = noteText;
            IstaNoteClient.IstaNoteService.CreateResponse retVal = ((IstaNoteClient.IstaNoteService.NoteSoap)(this)).Create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.CreateResponse> IstaNoteClient.IstaNoteService.NoteSoap.CreateAsync(IstaNoteClient.IstaNoteService.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.CreateResponse> CreateAsync(string accountNo, IstaNoteClient.IstaNoteService.NoteStatusOptions noteStatus, IstaNoteClient.IstaNoteService.NotePriorityOptions notePriority, int noteTypeID, int noteTypeDetailId, int noteDepartmentId, int openByUserId, System.DateTime callBegin, System.DateTime callEnd, System.DateTime closeDate, IstaNoteClient.IstaNoteService.NoteCallTypeOptions callType, string noteText) {
            IstaNoteClient.IstaNoteService.CreateRequest inValue = new IstaNoteClient.IstaNoteService.CreateRequest();
            inValue.Body = new IstaNoteClient.IstaNoteService.CreateRequestBody();
            inValue.Body.accountNo = accountNo;
            inValue.Body.noteStatus = noteStatus;
            inValue.Body.notePriority = notePriority;
            inValue.Body.noteTypeID = noteTypeID;
            inValue.Body.noteTypeDetailId = noteTypeDetailId;
            inValue.Body.noteDepartmentId = noteDepartmentId;
            inValue.Body.openByUserId = openByUserId;
            inValue.Body.callBegin = callBegin;
            inValue.Body.callEnd = callEnd;
            inValue.Body.closeDate = closeDate;
            inValue.Body.callType = callType;
            inValue.Body.noteText = noteText;
            return ((IstaNoteClient.IstaNoteService.NoteSoap)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IstaNoteClient.IstaNoteService.ListResponse IstaNoteClient.IstaNoteService.NoteSoap.List(IstaNoteClient.IstaNoteService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public IstaNoteClient.IstaNoteService.NoteDTO[] List(int customerId, string accountNo) {
            IstaNoteClient.IstaNoteService.ListRequest inValue = new IstaNoteClient.IstaNoteService.ListRequest();
            inValue.Body = new IstaNoteClient.IstaNoteService.ListRequestBody();
            inValue.Body.customerId = customerId;
            inValue.Body.accountNo = accountNo;
            IstaNoteClient.IstaNoteService.ListResponse retVal = ((IstaNoteClient.IstaNoteService.NoteSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.ListResponse> IstaNoteClient.IstaNoteService.NoteSoap.ListAsync(IstaNoteClient.IstaNoteService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<IstaNoteClient.IstaNoteService.ListResponse> ListAsync(int customerId, string accountNo) {
            IstaNoteClient.IstaNoteService.ListRequest inValue = new IstaNoteClient.IstaNoteService.ListRequest();
            inValue.Body = new IstaNoteClient.IstaNoteService.ListRequestBody();
            inValue.Body.customerId = customerId;
            inValue.Body.accountNo = accountNo;
            return ((IstaNoteClient.IstaNoteService.NoteSoap)(this)).ListAsync(inValue);
        }
    }
}
